
#type: args

train:
  epochs: 4000
  batch_size: 8 
  lr: 1.0e-3
  itr_per_epoch: 1.0e+8
  train_block: False


diffusion:
  layers: 4 
  channels: 32
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.3
  num_steps: 50
  schedule: "quad"
  is_linear: False
  DEVICE: 'cuda:0'
  num_of_vertices: 207
  seq_len: 72
  seq_hid: 128
  n_hid: 207
  dropout: 0.
  gama: 2


model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "mix"